name: Saludo

on:
  push:
    branches: ["main"]
    # opcional: ejecutar manualmente desde Actions
  workflow_dispatch:

jobs:
  saludar-al-usuario:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repo
        uses: actions/checkout@v4

      - name: Saludo
        run: echo "¡Hola, ${{ github.actor }}! Gracias por hacer push."

      - name: Listar archivos del repo
        run: ls -la
